openapi: 3.0.0
info:
  title: WIEDPUG API Specifications
  version: 1.0.0

servers:
  - url: https://example.com/v1

tags:
  - name: Organization Details
  
paths:
  /organization-details:
    get:
      tags:
      - Organization Details
      summary: Retrieve all organization details
      operationId: getAllOrganizationDetails
      responses:
        '200':
          description: A list of organization details
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/OrganizationDetails'
        '401':
          description: Unauthorized - login required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - lack of permission
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - Organization Details
      summary: Create a new organization details
      operationId: createOrganizationDetail
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrganizationDetails'
      responses:
        '201':
          description: The newly created organization detail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationDetails'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized - login required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - lack of permission
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Conflict - resource already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /organization-details/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
        description: The ID of the organization detail to operate on
    get:
      tags:
        - Organization Details
      summary: Retrieve a specific organization detail by its id
      operationId: getOrganizationDetailById
      responses:
        '200':
          description: The organization detail object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationDetails'
        '401':
          description: Unauthorized - login required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Organization detail not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      tags:
        - Organization Details
      summary: Update an existing organization details
      operationId: updateOrganizationDetail
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrganizationDetails'
      responses:
        '200':
          description: Updated organization detail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationDetails'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized - login required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - lack of permission
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Organization detail not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      tags:
        - Organization Details
      summary: Delete an organization details
      operationId: deleteOrganizationDetail
      responses:
        '204':
          description: Organization detail deleted
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized - login required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - lack of permission
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Organization detail not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    OrganizationDetails:
      type: object
      additionalProperties: false
      properties:
        transmissionHeader:
          $ref: '#/components/schemas/TransmissionHeader'
        organizationDetails:
          type: array
          items:
            $ref: '#/components/schemas/OrganizationDetail'
      required:
        - transmissionHeader
        - organizationDetails
      title: OrganizationDetails
    OrganizationDetail:
      type: object
      additionalProperties: false
      properties:
        id:
          type: string
          example: "43543763625"
        organisationCode:
          $ref: "#/components/schemas/OrganizationCode"
        nameOfOrganisation:
          type: string 
        dateLastUpdated:
          type: string
          format: date
          example: "2020-12-12"
        IndustryGroupID:
          type: string
          enum:
            - "A"
            - "C"
            - "E"
            - "D"
            - "M"
            - "P"
            - "S"
            - "T"
            - "V"
          description: >-
            The code used to indicate which industry group it belongs to,
            eg. Agent/Broker or Carrier.<br />A: Agent / Broker<br />C:
            Carrier<br /E: Exporter / Buyer<br />D: Dump<br
            />M: Miscellaneous<br />P: Port<br />S: Shipping<br />
            T: Test House<br />V: Vessel
        transmitterFlag:
          type: string
          enum:
            - 'Y'
            - 'N'
          description: >-
            <br />Y: The organisation transmits or receives data electronically<br />N: The organisation neither transmits nor receives data electronically
        abn:
          type: string
          nullable: true
        addresses:
          type: array
          items:
            $ref: '#/components/schemas/Address'
        contacts:
          type: array
          items:
            $ref: '#/components/schemas/Contact'
        faxNumber:
          $ref: '#/components/schemas/PhoneNumber'
        phoneNumber:
          $ref: '#/components/schemas/PhoneNumber'
      required:
        - dateLastUpdated
        - industryGroupID
        - nameOfOrganisation
        - organisationCode
      title: OrganizationDetail
    Address:
      type: object
      additionalProperties: false
      properties:
        firstName:
          type: string
          nullable: true
        lastName:
          type: string
          nullable: true
        organisationName:
          type: string
          nullable: true
        premise:
          type: string
          nullable: true
        street:
          type: string
          nullable: true
        suburb:
          type: string
          nullable: true
        city:
          type: string
          nullable: true
        regionOrState:
          type: string
          nullable: true
        postalCode:
          type: integer
          nullable: true
        country:
          type: string
          nullable: true
          example: "AU"
      required:
        - city
        - country
        - firstName
        - lastName
        - organisationName
        - postalCode
        - premise
        - regionOrState
        - street
        - suburb
      title: Address
    Contact:
      type: object
      additionalProperties: false
      properties:
        description:
          type: string
          nullable: true
        firstName:
          type: string
          nullable: true
        lastName:
          type: string
          nullable: true
        phoneNumber:
          $ref: '#/components/schemas/PhoneNumber'
          nullable: true
        mobileNumber:
          $ref: '#/components/schemas/PhoneNumber'
          nullable: true
        email:
          type: string
          nullable: true
          format: email
          example: "abbc@example.com"
      required:
        - description
        - email
        - firstName
        - lastName
        - phoneNumber
        - mobileNumber
      title: Contact
    PhoneNumber:
      type: object
      additionalProperties: false
      properties:
        countryCode:
          type: string
          nullable: true
        number:
          type: string
          nullable: true
      required:
        - countryCode
        - number
      title: PhoneNumber
    TransmissionHeader:
      type: object
      additionalProperties: false
      properties:
        countryOfOrigin:
          type: string
          example: "AU"
        documentOriginator:
          type: string
        currentTransmitter:
          type: string
        currentReceiver:
          type: string
        finalReceiver:
          type: string
        softwareIdentifier:
          type: string
          nullable: true
        abn:
          type: string
          nullable: true
      required:
        - abn
        - countryOfOrigin
        - currentReceiver
        - currentTransmitter
        - documentOriginator
        - finalReceiver
        - softwareIdentifier
      title: TransmissionHeader
    OrganizationCode:
      type: string
      example: "AWTS"
      description:  Wool Industry Organisation Code
    Error:
      type: object
      description: Error
      properties:
        errorCode:
          type: string
          description: Error code
        errorMessage:
          type: string
          description: Error Message