openapi: 3.0.0
info:
  title: Shared components
  version: 1.0.0
components:
  schemas:
    Scope:
      type: object
      additionalProperties: false
      properties:
        id:
          type: string
          example: "100200001"
        documentType:
          $ref: '#/components/schemas/DocumentType'
        documentId:
          type: string
        owner:
          $ref: '#/components/schemas/OrganizationCode'
        sendType:
          type: string
          enum:
            - "PRIVATE"
            - "BORADCAST"
        receivers:
          type: array
          items:
            $ref: '#/components/schemas/OrganizationCode'
        privateRecords:
          type: array
          items:
            $ref: '#/components/schemas/PrivateRecord'
      required:
        - id
        - documentType
        - documentId
        - creator
        - receviers
        - sendType
        - privateRecords
      title: Scope
    Address:
      type: object
      additionalProperties: false
      properties:
        firstName:
          type: string
          nullable: true
        lastName:
          type: string
          nullable: true
        organisationName:
          type: string
          nullable: true
        premise:
          type: string
          nullable: true
        street:
          type: string
          nullable: true
        suburb:
          type: string
          nullable: true
        city:
          type: string
          nullable: true
        regionOrState:
          type: string
          nullable: true
        postalCode:
          type: integer
          nullable: true
        country:
          type: string
          nullable: true
          example: "AU"
      required:
        - city
        - country
        - firstName
        - lastName
        - organisationName
        - postalCode
        - premise
        - regionOrState
        - street
        - suburb
      title: Address
    Contact:
      type: object
      additionalProperties: false
      properties:
        description:
          type: string
          nullable: true
        name:
          type: string
          nullable: true
        phoneNumber:
          $ref: '#/components/schemas/PhoneNumber'
          nullable: true
        mobileNumber:
          $ref: '#/components/schemas/PhoneNumber'
          nullable: true
        email:
          type: string
          nullable: true
          example: "abbc@example.com"
      required:
        - description
        - email
        - name
        - phoneNumber
        - mobileNumber
      title: Contact
    PhoneNumber:
      type: object
      additionalProperties: false
      properties:
        countryCode:
          type: string
          nullable: true
        number:
          type: string
          nullable: true
      required:
        - countryCode
        - number
      title: PhoneNumber
    TransmissionHeader:
      type: object
      additionalProperties: false
      properties:
        dateFormatLastRevised:
          type: string
          format: date
          example: "2021-01-11"
        dateTransmissionFileCreated:
          type: string
          format: date
          example: "2021-01-11"
        countryOfOrigin:
          type: string
          example: "AU"
        documentOriginator:
          type: string
        currentTransmitter:
          type: string
        currentReceiver:
          type: string
        finalReceiver:
          type: string
        accessPassword:
          type: string
          nullable: true
          format: password
        accessPasswordReplacement:
          type: string
          nullable: true
          format: password
        transmissionType:
          type: string
          format: integer
        versionNumber:
          type: integer
          nullable: true
        softwareIdentifier:
          type: string
          nullable: true
        abn:
          type: string
          nullable: true
      required:
        - abn
        - accessPassword
        - accessPasswordReplacement
        - countryOfOrigin
        - currentReceiver
        - currentTransmitter
        - dateFormatLastRevised
        - dateTransmissionFileCreated
        - documentOriginator
        - finalReceiver
        - softwareIdentifier
        - transmissionType
        - versionNumber
      title: TransmissionHeader
    OrganizationCode:
      type: string
      example: "AWTS"
    PrivateRecord:
      type: object
      additionalProperties: false
      properties:
        recordName:
          type: string
        recordId:
          type: string
        privateViewers:
          type: array
          items:
            $ref: "#/components/schemas/OrganizationCode"
      required:
        - recordName
        - recordId
        - privateViewers
      title: PrivateRecord
    DocumentType:
      type: string
      enum:
        - "AC"
        - "ACK"
        - "ACU"
        - "DO"
        - "DRV"
        - "DS"
        - "GI"
        - "LI"
        - "LPD"
        - "OD"
        - "PA"
        - "PCF"
        - "PC"
        - "SR"
        - "ST"
        - "TC"
        - "TCR"
        - "TCU"
        - "TRV"
        - "TS"
        - "TXT" 
    Error:
      type: object
      description: Error
      properties:
        errorCode:
          type: string
          description: Error code
        errorMessage:
          type: string
          description: Error Message